spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  application:
    name: metrics-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  data:
    mongodb:
      uri: ${MONGODB_URI}
  aop:
    proxy-target-class: true
  main:
    allow-bean-definition-overriding: true

debug: ${DEBUG}
server:
  port: ${PORT}
  error:
    include-stacktrace: on_trace_param

logging:
  level:
    org.springframework: error
    com.metrics.metricsservice: ${LOG_LEVEL}
black-list: ${BLACK_LIST}
jwt:
  secret: ${JWT_SECRET}
  token-expire-time: ${JWT_TOKEN_EXPIRE_TIME}
  token-refresh-expire-time: ${JWT_TOKEN_REFRESH_EXPIRE_TIME}
